# Generated by Django 5.0.1 on 2024-11-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='detail_image',
            field=models.ImageField(null=True, upload_to='product_detail/'),
        ),
    ]
