# Generated by Django 5.0.1 on 2024-11-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productimage_detail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
