# Generated by Django 5.0.1 on 2024-11-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Moderation'), (3, 'Sold'), (4, 'Inactive')], default=1),
        ),
    ]
